#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
tbs_full_dependencies:
  enabled: true
  pkgr_version: 1.10.8
  pkgr_repo_url: harbor.tap.h2o-3-16879.h2o.vmware.com/tap-packages/tbs-full-deps:1.10.8
acs:
  enabled: true
  pkgr_version: 2.0.0
scg:
  enabled: true
  pkgr_version: 2.0.0-tap.3
